services:
  client:
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - server

  server:
    restart: always
    build:
      context: ./server
      target: development
    environment:
      - PG_DBNAME=wellness_map
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=password
      - JWT_SECRET=03c45d79b7e0aac8aac3f41711eed8f962bac31c7c26dde8f43d8aa9b2a46ab8
      - PORT=5001
      - PG_PORT=5432
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - express-db
      - react-express
    ports:
      - "5001:5001"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - express-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  react-express:
  express-db:

volumes:
  db-data: